-- obiekt AUTO
CREATE TYPE AUTO AS OBJECT
(
  MARKA          VARCHAR2(20),
  MODEL          VARCHAR2(20),
  KILOMETRY      NUMBER,
  DATA_PRODUKCJI DATE,
  CENA           NUMBER(10, 2),
  MEMBER FUNCTION WARTOSC RETURN NUMBER
)
NOT FINAL;

-- implementacja funkcji wartosc
CREATE OR REPLACE TYPE BODY AUTO AS
  MEMBER FUNCTION WARTOSC RETURN NUMBER IS
    WIEK    NUMBER;
    WARTOSC NUMBER;
  BEGIN
    WIEK    := ROUND(MONTHS_BETWEEN(SYSDATE, DATA_PRODUKCJI) / 12);
    WARTOSC := CENA - (WIEK * 0.1 * CENA);
    IF (WARTOSC < 0) THEN
      WARTOSC := 0;
    END IF;
    RETURN WARTOSC;
  END WARTOSC;
END;

-- tabela obiektowa AUTA
CREATE TABLE AUTA OF AUTO;
INSERT INTO AUTA VALUES (AUTO('FIAT','BRAVA',60000,DATE '1999-11-30',25000));
INSERT INTO AUTA VALUES (AUTO('FORD','MONDEO',80000,DATE '1997-05-10',45000));
INSERT INTO AUTA VALUES (AUTO('MAZDA','323',12000,DATE '2000-09-22',52000));

--obiekt AUTO_OSOBOWE dziedziczace po obiekcie AUTO
CREATE TYPE AUTO_OSOBOWE UNDER AUTO
(
  miejsca_ilosc NUMBER,
  klimatyzacja  VARCHAR2(3),
  OVERRIDING MEMBER FUNCTION WARTOSC RETURN NUMBER
)
; 

--obiekt AUTO_CIEZAROWE dziedziczace po obiekcie AUTO
CREATE TYPE AUTO_CIEZAROWE UNDER AUTO
(
  LADOWNOSC NUMBER,
  OVERRIDING MEMBER FUNCTION WARTOSC RETURN NUMBER
)
; 

--implementacja funkcji WARTOSC dla obiektu AUTO_OSOBOWE
CREATE OR REPLACE TYPE BODY AUTO_OSOBOWE AS
  OVERRIDING MEMBER FUNCTION WARTOSC RETURN NUMBER IS
    WIEK    NUMBER;
    WARTOSC NUMBER;
  BEGIN
    WIEK    := ROUND(MONTHS_BETWEEN(SYSDATE, DATA_PRODUKCJI) / 12);
    IF KLIMATYZACJA = 'TAK' THEN
       WARTOSC := (CENA - (WIEK * 0.1 * CENA)) * 0.5;
    ELSE
      WARTOSC := CENA - (WIEK * 0.1 * CENA);
    END IF;
    
    IF (WARTOSC < 0) THEN
      WARTOSC := 0;
    END IF;
    RETURN WARTOSC;
  END WARTOSC;
END;


--implementacja funkcji WARTOSC dla obiektu AUTO_CIEZAROWE
CREATE OR REPLACE TYPE BODY AUTO_CIEZAROWE AS
  OVERRIDING MEMBER FUNCTION WARTOSC RETURN NUMBER IS
    WIEK    NUMBER;
    WARTOSC NUMBER;
  BEGIN
    WIEK    := ROUND(MONTHS_BETWEEN(SYSDATE, DATA_PRODUKCJI) / 12);
    IF LADOWNOSC > 10000 THEN
       WARTOSC := CENA - (WIEK * 0.1 * CENA);
       WARTOSC := WARTOSC + WARTOSC;
    ELSE
      WARTOSC := CENA - (WIEK * 0.1 * CENA) * 0.5;
    END IF;
    
    IF (WARTOSC < 0) THEN
      WARTOSC := 0;
    END IF;
    RETURN WARTOSC;
  END WARTOSC;
END;

--DROP TABLE AUTA;
--tabela obiektowa 
CREATE TABLE AUTA OF AUTO;
INSERT INTO auta VALUES ( AUTO_OSOBOWE('FIAT','BRAVA',60000,DATE '1999-11-30',25000,4,'TAK' ) );
INSERT INTO auta VALUES ( AUTO_OSOBOWE('RENAULT','LAGUNA',4500,DATE '2010-11-30',19000,6,'NIE' ) );
INSERT INTO auta VALUES ( AUTO_CIEZAROWE('ZUK','STARY',1500,DATE '2012-11-30',15000,8000) );
INSERT INTO auta VALUES ( AUTO_CIEZAROWE('STAR','RUSKI',666,DATE '2011-11-30',35555,120000)  );
INSERT INTO auta VALUES (AUTO('FIAT','BRAVA',60000,DATE '1999-11-30',25000));
INSERT INTO auta VALUES (AUTO('FORD','MONDEO',80000,DATE '1997-05-10',45000));
INSERT INTO auta VALUES (AUTO('MAZDA','323',12000,DATE '2000-09-22',52000));

SELECT a.*, a.wartosc() FROM auta a;



