CREATE TABLE PISARZE (
 ID_PISARZA NUMBER PRIMARY KEY,
 NAZWISKO VARCHAR2(20),
 DATA_UR DATE );
 
CREATE TABLE KSIAZKI (
 ID_KSIAZKI NUMBER PRIMARY KEY,
 ID_PISARZA NUMBER NOT NULL REFERENCES PISARZE,
 TYTUL VARCHAR2(50),
 DATA_WYDANIA DATE );
 
INSERT INTO PISARZE VALUES (10, 'SIENKIEWICZ', DATE '1880-01-01');
INSERT INTO PISARZE VALUES (20, 'PRUS', DATE '1890-04-12');
INSERT INTO PISARZE VALUES (30, 'ZEROMSKI', DATE '1899-09-11');

INSERT INTO KSIAZKI
  (ID_KSIAZKI, ID_PISARZA, TYTUL, DATA_WYDANIA)
VALUES
  (10, 10, 'OGNIEM I MIECZEM', DATE '1990-01-05');
INSERT INTO KSIAZKI
  (ID_KSIAZKI, ID_PISARZA, TYTUL, DATA_WYDANIA)
VALUES
  (20, 10, 'POTOP', DATE '1975-12-09');
INSERT INTO KSIAZKI
  (ID_KSIAZKI, ID_PISARZA, TYTUL, DATA_WYDANIA)
VALUES
  (30, 10, 'PAN WOLODYJOWSKI', DATE '1987-02-15');
INSERT INTO KSIAZKI
  (ID_KSIAZKI, ID_PISARZA, TYTUL, DATA_WYDANIA)
VALUES
  (40, 20, 'FARAON', DATE '1948-01-21');
INSERT INTO KSIAZKI
  (ID_KSIAZKI, ID_PISARZA, TYTUL, DATA_WYDANIA)
VALUES
  (50, 20, 'LALKA', DATE '1994-08-01');
INSERT INTO KSIAZKI
  (ID_KSIAZKI, ID_PISARZA, TYTUL, DATA_WYDANIA)
VALUES
  (60, 30, 'PRZEDWIOSNIE', DATE '1938-02-02');
 
--pomocniczna struktura  
CREATE TYPE KSIAZKI_TAB AS TABLE OF VARCHAR2(100);

--obiekt Pisarz
 CREATE TYPE PISARZ AS OBJECT (
 ID_PISARZA NUMBER,
 NAZWISKO VARCHAR2(20),
 DATA_UR DATE,
 KSIAZKI KSIAZKI_TAB,
 MEMBER FUNCTION ILE_KSIAZEK RETURN NUMBER
);

--implementacja funkcji
CREATE OR REPLACE TYPE BODY PISARZ AS
  MEMBER FUNCTION ILE_KSIAZEK RETURN NUMBER IS
  BEGIN
    RETURN KSIAZKI.COUNT();
  END ILE_KSIAZEK;
END;

-- widok z wykorzystaniem obiektu PISARZ
CREATE OR REPLACE VIEW PISARZE_V OF PISARZ
WITH OBJECT IDENTIFIER (ID_PISARZA)
AS SELECT ID_PISARZA, NAZWISKO, DATA_UR,
 CAST(MULTISET( SELECT TYTUL FROM KSIAZKI WHERE ID_PISARZA=P.ID_PISARZA ) AS KSIAZKI_TAB )
FROM PISARZE P;

--obiekt typu KSIAZKA
CREATE TYPE KSIAZKA AS OBJECT
(
  ID_KSIAZKI     NUMBER,
  ID_PISARZA     REF PISARZ,
  TYTUL          VARCHAR2(50),
  DATA_WYDANIA   DATE,
  MEMBER FUNCTION ILE_LAT RETURN NUMBER
);

--implementacja funkcji
CREATE OR REPLACE TYPE BODY KSIAZKA AS
  MEMBER FUNCTION ILE_LAT RETURN NUMBER IS
  BEGIN
    RETURN to_char(sysdate,'YYYY') - to_char(DATA_WYDANIA,'YYYY');
  END ILE_LAT;
END;

-- widok z wykorzystaniem obiektu KSIAZKA
CREATE OR REPLACE VIEW KSIAZKI_V OF KSIAZKA
WITH OBJECT IDENTIFIER (ID_KSIAZKI)
AS SELECT ID_KSIAZKI,  MAKE_REF(PISARZE_V,ID_PISARZA), TYTUL, DATA_WYDANIA
FROM KSIAZKI K; 

SELECT * FROM PISARZE_V;

SELECT P.NAZWISKO, P.DATA_UR, p.KSIAZKI FROM PISARZE_V P;

SELECT P.NAZWISKO, P.DATA_UR, P.ILE_KSIAZEK(),P.KSIAZKI FROM PISARZE_V P;

SELECT NAZWISKO,
       CURSOR (SELECT KSIAZKI FROM PISARZE_V WHERE ID_PISARZA = P.ID_PISARZA)
  FROM PISARZE_V P;
  

SELECT K.ID_KSIAZKI,K.TYTUL, K.DATA_WYDANIA,K.ILE_LAT() from KSIAZKI_V K

